import { type NextPage } from "next";
import Head from "next/head";
import Dashboard from "@components/dashboard";
import Layout from "@components/dashboard/layout/index";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Dashboard />
      </Layout>
    </>
  );
};

export default Home;
